local sound_api = {
    node_sound_default         = nodes_nature.node_sound_default,
    node_sound_stone_defaults  = nodes_nature.node_sound_stone_defaults,
    node_sound_dirt_defaults   = nodes_nature.node_sound_dirt_defaults,
    node_sound_grass_defaults  = nodes_nature.node_sound_dirt_defaults,
    node_sound_sand_defaults   = nodes_nature.node_sound_sand_defaults,
    node_sound_gravel_defaults = nodes_nature.node_sound_gravel_defaults,
    node_sound_wood_defaults   = nodes_nature.node_sound_wood_defaults,
    node_sound_leaves_defaults = nodes_nature.node_sound_leaves_defaults,
    node_sound_glass_defaults  = nodes_nature.node_sound_glass_defaults,
    node_sound_ice_defaults    = nodes_nature.node_sound_glass_defaults,
    node_sound_metal_defaults  = nodes_nature.node_sound_default,
    node_sound_water_defaults  = nodes_nature.node_sound_water_defaults,
    node_sound_lava_defaults   = nodes_nature.node_sound_water_defaults,
    node_sound_snow_defaults   = nodes_nature.node_sound_snow_defaults,
    node_sound_wool_defaults   = nodes_nature.node_sound_default,


    node = {
        dig = {
            default            = "nodes_nature_dig_crumbly",
            bushy              = nil,
            choppy             = "nodes_nature_dig_choppy",
            clanky             = "nodes_nature_hard_footstep",
            cracky             = "nodes_nature_dig_cracky",
            crumbly            = "nodes_nature_dig_crumbly",
            earthy             = "nodes_nature_dig_crumbly",
            fleshy             = "nodes_nature_dig_crumbly",
            glassy             = "nodes_nature_glass_footstep",
            grassy             = "nodes_nature_dig_crumbly",
            icy                = "nodes_nature_dig_cracky",
            pebbly             = "nodes_nature_dig_crumbly",
            sandy              = "nodes_nature_dig_crumbly",
            seedy              = nil,
            snappy             = "nodes_nature_dig_snappy", -- alternative: "snappy"
            snowy              = "nodes_nature_dig_crumbly",
            splashy            = "animals_water_swish",
            stony              = "nodes_nature_hard_footstep",
            wooly              = "nodes_nature_dig_crumbly",
        },
        dug = {
            default            = "nodes_nature_dug_node",
            bushy              = nil,
            choppy             = "nodes_nature_dug_node",
            clanky             = "nodes_nature_dug_node",
            cracky             = "nodes_nature_dug_node",
            crumbly            = "nodes_nature_dug_node",
            earthy             = "nodes_nature_dug_node",
            fleshy             = "nodes_nature_dug_node",
            glassy             = "default_break_glass", -- alternative: "nodes_nature_remove_glass"
            grassy             = "nodes_nature_dug_node",
            icy                = "default_break_glass",
            pebbly             = "nodes_nature_dug_node",
            sandy              = "nodes_nature_dug_node",
            seedy              = nil,
            snappy             = "nodes_nature_dug_node",
            snowy              = "nodes_nature_dug_node",
            splashy            = nil,
            stony              = "nodes_nature_dug_node",
            wooly              = "nodes_nature_dug_node",
        },
        place = {
            default            = "nodes_nature_place_node",
            bushy              = nil,
            choppy             = "nodes_nature_place_node_hard",
            clanky             = "nodes_nature_place_node",
            cracky             = "nodes_nature_place_node",
            crumbly            = "nodes_nature_place_node",
            earthy             = "nodes_nature_place_node",
            fleshy             = "nodes_nature_place_node",
            glassy             = "nodes_nature_place_glass",
            grassy             = "nodes_nature_place_node",
            icy                = "nodes_nature_place_glass",
            pebbly             = "nodes_nature_place_node",
            sandy              = "nodes_nature_place_node",
            seedy              = nil,
            snappy             = "nodes_nature_place_node",
            snowy              = "nodes_nature_place_node",
            splashy            = nil,
            stony              = "nodes_nature_place_node_hard",
            wooly              = "nodes_nature_place_node",
        },
        step = {
            default            = "nodes_nature_dirt_footstep",
            bouncy             = nil,
            bushy              = nil,
            choppy             = "nodes_nature_wood_footstep",
            clanky             = "nodes_nature_hard_footstep",
            cracky             = "nodes_nature_glass_footstep",
            crumbly            = "nodes_nature_sand_footstep",
            earthy             = "nodes_nature_dirt_footstep",
            glassy             = "nodes_nature_glass_footstep",
            grassy             = "nodes_nature_grass_footstep",
            icy                = "nodes_nature_glass_footstep",
            muddy              = "nodes_nature_mud",
            pebbly             = "nodes_nature_gravel_footstep",
            sandy              = "nodes_nature_sand_footstep",
            snappy             = "nodes_nature_dirt_footstep",
            snowy              = "nodes_nature_snow_footstep",
            splashy            = "nodes_nature_water_footstep",
            squishy            = "nodes_nature_mud",
            stony              = "nodes_nature_hard_footstep",
            wooly              = "nodes_nature_dirt_footstep",

            ladder = {
                default        = nil,
                metal          = nil,
                wood           = nil,
            },
        },
    },

    entity = {
        damage = {
            default            = "player_damage",
            player             = "player_damage",
            player_fall        = "player_damage",
            bony               = "player_damage",
            choppy             = "player_damage",
            clanky             = "player_damage",
            cracky             = "player_damage",
            crumbly            = "player_damage",
            earthy             = "player_damage",
            fleshy             = "animals_punch",
            glassy             = "player_damage",
            icy                = "player_damage",
            pebbly             = "player_damage",
            sandy              = "player_damage",
            snappy             = "player_damage",
            snowy              = "player_damage",
            splashy            = "player_damage",
            stony              = "player_damage",
            wooly              = "player_damage",
        },
        die = {
            default            = nil,
            player             = "health_vomit",
            bony               = nil,
            choppy             = nil,
            clanky             = nil,
            cracky             = nil,
            crumbly            = nil,
            earthy             = nil,
            fleshy             = nil,
            glassy             = nil,
            icy                = nil,
            pebbly             = nil,
            sandy              = nil,
            snappy             = nil,
            snowy              = nil,
            splashy            = nil,
            stony              = nil,
            wooly              = nil,
        },
    },

    item = {
        drop                   = nil,
        pickup                 = nil,

        tool = {
            broken             = "tech_tool_breaks",
            flint              = "inferno_fire_sticks",
            hammer             = nil,
            hit                = "spears_hit",
            screwdriver        = nil,
            swing              = "spears_throw",
            throw              = "spears_throw",
            use                = nil,
        },
    },
    door = {
        close                  = "doors_door_close",
        close_bar              = nil,
        close_glass            = "doors_glass_door_close",
        close_metal            = "doors_steel_door_close",
        close_stone            = nil,
        close_wood             = "doors_door_close",
        lock                   = nil,
        locked                 = nil,
        locked_glass           = nil,
        locked_metal           = nil,
        locked_stone           = nil,
        locked_wood            = nil,
        open                   = "doors_door_open",
        open_bar               = nil,
        open_glass             = "doors_glass_door_open",
        open_metal             = "doors_steel_door_open",
        open_stone             = nil,
        open_wood              = "doors_door_open",
        slam                   = nil,
        slam_glass             = nil,
        slam_metal             = nil,
        slam_stone             = nil,
        slam_wood              = nil,
        slide                  = nil,
        slide_glass            = nil,
        slide_metal            = nil,
        slide_stone            = nil,
        slide_wood             = nil,
        unlock                 = nil,
    },
    gate = {
        close                  = "doors_fencegate_close",
        close_stone            = nil,
        close_wood             = nil,
        locked                 = nil,
        locked_wood            = nil,
        open                   = "doors_fencegate_open",
        open_stone             = nil,
        open_wood              = nil,
    },
    chest = {
        close                  = "doors_door_close",
        locked                 = nil,
        open                   = "doors_door_open",
    },
    lever = {
        up                     = nil,
        down                   = nil,
        fail                   = nil,
    },

    env = {
        bones                  = nil,
        creak                  = "ropes_creak",
        smoke                  = nil,

        explosive = {
            boom               = nil,
            boom_light         = nil,
            boom_heavy         = nil,
            ignite_fuse        = nil,
            ignite_powder      = nil,
        },
        fire = {
            burn               = nil,
            burn_light         = nil,
            burn_heavy         = nil,
            combust            = nil,
            extinguish         = "inferno_extinguish_flame",
            flame              = nil,
            flame_light        = "tech_fire_small",
            flame_heavy        = nil,
        },
        lava = {
            cool               = "nodes_nature_cool_lava",
            flow               = nil,
            flow_light         = nil,
            flow_heavy         = nil,
            splash             = nil,
            splash_light       = nil,
            splash_heavy       = nil,
        },
        liquid = {
            bubble             = nil,
            bubble_light       = nil,
            bubble_heavy       = nil,
            drain              = nil,
            drip               = "nodes_nature_water_drip",
            drip_light         = nil,
            drip_heavy         = nil,
            fill               = nil,
            flow               = nil,
            flow_light         = nil,
            flow_heavy         = nil,
            freeze             = nil,
            freeze_light       = nil,
            freeze_heavy       = nil,
            scald              = nil,
            scald_light        = nil,
            scald_heavy        = nil,
            splash             = nil,
            splash_light       = nil,
            splash_heavy       = nil,
            waves              = nil,
            waves_light        = nil,
            waves_heavy        = nil,
        },
        tech = {
            beep               = nil,
            bell               = nil,
            ding               = nil,
            doorbell           = nil,
            hammer             = "tech_hammer",
        },
        weather = {
            thunder = {
                clap           = "lightning_thunder",
                clap_light     = nil,
                clap_heavy     = nil,
                roll           = nil,
                roll_light     = nil,
                roll_heavy     = nil,
            },
            wind = {
                gust           = nil,
                gust_light     = nil,
                gust_heavy     = nil,
            },
        },
    },

    loop = {
        cook = {
            fry                = "tech_frying",
        },
        explosive = {
            burn_fuse          = nil,
            burn_powder        = nil,
        },
        fire = {
            burn               = "inferno_fire",
            burn_light         = "inferno_small",
            burn_heavy         = "inferno_large",
            furnace            = "tech_fire_small",
        },
        lava = {
            bubble             = nil,
            bubble_light       = nil,
            bubble_heavy       = nil,
            flow               = "env_sounds_lava",
            flow_light         = nil,
            flow_heavy         = nil,
        },
        liquid = {
            boil               = "tech_boil",
            boil_light         = nil,
            boil_heavy         = nil,
            bubble             = nil,
            bubble_light       = nil,
            bubble_heavy       = nil,
            flow               = "env_sounds_water",
            flow_light         = nil,
            flow_heavy         = nil,
            waves              = "env_sounds_waves",
            waves_light        = nil,
            waves_heavy        = nil,
        },
        tech = {
            bell               = nil,
            bells              = nil,
            microwave          = nil,
            oven               = nil,
        },
        weather = {
            rain               = "rain_loop",
            rain_light         = "light_rain_loop",
            rain_heavy         = "heavy_rain_loop",
            snow               = "snowstorm_loop",
            snow_light         = "snowstorm_loop_light",
            snow_heavy         = nil,
            wind               = "duststorm_loop",
            wind_light         = "env_sounds_wind_light", -- alternative: "duststorm_loop_light"
            wind_heavy         = "env_sounds_wind_strong",
        },
    },

    notify = {
        default                = nil,
        achievement            = nil,
        click                  = nil,
        click_alt              = nil,
        ding                   = nil,
        drink                  = nil,
        eat                    = nil,
        experience             = nil,
        err                    = nil,
        greeting               = nil,
        level_up               = nil,
        level_down             = nil,
        mode                   = nil,
        ping                   = nil,
        respawn                = nil,
        skin                   = nil,
        teleport               = nil,
        toast                  = nil,
        trash                  = nil,

        gui = {
            button             = nil,
            select             = nil,
            tab                = nil,
        },
    },
}

return sound_api
