local sound_api = {
    node_sound_default         = hades_sounds.node_sound_defaults,
    node_sound_stone_defaults  = hades_sounds.node_sound_stone_defaults,
    node_sound_dirt_defaults   = hades_sounds.node_sound_dirt_defaults,
    node_sound_grass_defaults  = hades_sounds.node_sound_grass_defaults,
    node_sound_sand_defaults   = hades_sounds.node_sound_sand_defaults,
    node_sound_gravel_defaults = hades_sounds.node_sound_gravel_defaults,
    node_sound_wood_defaults   = hades_sounds.node_sound_wood_defaults,
    node_sound_leaves_defaults = hades_sounds.node_sound_leaves_defaults,
    node_sound_glass_defaults  = hades_sounds.node_sound_glass_defaults,
    node_sound_ice_defaults    = hades_sounds.node_sound_glass_defaults,
    node_sound_metal_defaults  = hades_sounds.node_sound_metal_defaults,
    node_sound_water_defaults  = hades_sounds.node_sound_water_defaults,
    node_sound_lava_defaults   = hades_sounds.node_sound_lava_defaults,
    node_sound_snow_defaults   = hades_sounds.node_sound_dirt_defaults,
    node_sound_wool_defaults   = hades_sounds.node_sound_defaults,


    node = {
        dig = {
            default            = "default_dig_oddly_breakable_by_hand",
            bushy              = "hades_sounds_grass_dig",
            choppy             = "default_dig_choppy",
            clanky             = "default_dig_metal",
            cracky             = "default_dig_cracky",
            crumbly            = "default_dig_crumbly",
            earthy             = "hades_sounds_straw_dig",
            fleshy             = nil,
            glassy             = "default_dig_cracky",
            grassy             = "hades_sounds_grass_dig",
            icy                = "default_dig_cracky",
            pebbly             = "hades_sounds_gravel_dug",
            sandy              = "hades_sounds_ash_dig",
            seedy              = "hades_seeds_seed_dig",
            snappy             = "hades_sounds_straw_dig",
            snowy              = nil,
            splashy            = nil,
            stony              = "default_dig_choppy",
            wooly              = nil,
        },
        dug = {
            default            = "default_dug_node",
            bushy              = "hades_sounds_bush_dug",
            choppy             = "default_dig_choppy",
            clanky             = "default_dug_metal",
            cracky             = "default_glass_dug",
            crumbly            = nil,
            earthy             = "hades_sounds_straw_dug",
            fleshy             = "player_falling_damage",
            glassy             = "default_glass_dug",
            grassy             = "hades_sounds_grass_dug",
            icy                = "default_glass_dug",
            pebbly             = "hades_sounds_gravel_dug",
            sandy              = nil,
            seedy              = "hades_seeds_seed_dug",
            snappy             = "hades_sounds_straw_dug",
            snowy              = nil,
            splashy            = nil,
            stony              = "default_dig_choppy",
            wooly              = nil,
        },
        place = {
            default            = "default_place_node",
            bushy              = nil,
            choppy             = "default_place_node_hard",
            clanky             = "default_place_node_metal",
            cracky             = "default_glass_place",
            crumbly            = nil,
            earthy             = nil,
            fleshy             = nil,
            glassy             = "default_glass_place",
            grassy             = "hades_sounds_grass_place",
            icy                = "default_glass_place",
            pebbly             = nil,
            sandy              = nil,
            seedy              = "hades_seeds_seed_place",
            snappy             = "hades_sounds_straw_place",
            snowy              = nil,
            splashy            = "default_place_node_water",
            stony              = "default_place_node_hard",
            wooly              = nil,
        },
        step = {
            default            = "default_dirt_footstep",
            bouncy             = nil,
            bushy              = "hades_sounds_straw_footstep",
            choppy             = "default_wood_footstep",
            clanky             = "default_metal_footstep",
            cracky             = "default_glass_footstep",
            crumbly            = nil,
            earthy             = "default_dirt_footstep",
            glassy             = "default_glass_footstep",
            grassy             = "default_grass_footstep",
            icy                = "default_glass_footstep",
            muddy              = "hades_farming_wet_soil_footstep",
            pebbly             = "default_gravel_footstep",
            sandy              = "hades_sounds_ash_footstep",
            snappy             = "hades_sounds_straw_footstep",
            snowy              = nil,
            splashy            = "default_water_footstep",
            squishy            = nil,
            stony              = "default_hard_footstep",
            wooly              = "hades_sounds_cloth_footstep",

            ladder = {
                default        = "hades_core_footstep_ladder_wood",
                metal          = "hades_core_footstep_ladder_metal",
                wood           = "hades_core_footstep_ladder_wood",
            },
        },
    },

    entity = {
        damage = {
            default            = "mobs_punch",
            player             = "player_damage",
            player_fall        = "player_falling_damage",
            bony               = "mobs_punch",
            choppy             = "mobs_punch",
            clanky             = "mobs_punch",
            cracky             = "mobs_punch",
            crumbly            = "mobs_punch",
            earthy             = "mobs_punch",
            fleshy             = "mobs_punch",
            glassy             = "mobs_punch",
            icy                = "mobs_punch",
            pebbly             = "mobs_punch",
            sandy              = "mobs_punch",
            snappy             = "mobs_punch",
            snowy              = "mobs_punch",
            splashy            = "mobs_punch",
            stony              = "mobs_punch",
            wooly              = "mobs_punch",
        },
        die = {
            default            = nil,
            player             = "hades_player_death",
            bony               = nil,
            choppy             = nil,
            clanky             = nil,
            cracky             = nil,
            crumbly            = nil,
            earthy             = nil,
            fleshy             = nil,
            glassy             = "default_break_glass",
            icy                = nil,
            pebbly             = nil,
            sandy              = nil,
            snappy             = nil,
            snowy              = nil,
            splashy            = nil,
            stony              = nil,
            wooly              = nil,
        },
    },

    item = {
        drop                   = "item_drop",
        pickup                 = "item_drop_pickup",

        tool = {
            broken             = nil,
            flint              = nil,
            hammer             = nil,
            hit                = nil,
            screwdriver        = "screwdriver_use",
            swing              = "mobs_swing",
            throw              = nil,
            use                = nil,
        },
    },
    door = {
        close                  = "doors_door_close",
        close_bar              = "doors_door_steel_bar_close",
        close_glass            = "doors_glass_door_close",
        close_metal            = "doors_steel_door_close",
        close_stone            = nil,
        close_wood             = "doors_door_close",
        lock                   = "doors_door_locking",
        locked                 = "doors_door_locked",
        locked_glass           = nil,
        locked_metal           = nil,
        locked_stone           = "doors_door_locked_stone",
        locked_wood            = nil,
        open                   = "doors_door_open",
        open_bar               = "doors_door_steel_bar_open",
        open_glass             = "doors_glass_door_open",
        open_metal             = "doors_steel_door_open",
        open_stone             = nil,
        open_wood              = "doors_door_open",
        slam                   = nil,
        slam_glass             = nil,
        slam_metal             = nil,
        slam_stone             = nil,
        slam_wood              = nil,
        slide                  = nil,
        slide_glass            = nil,
        slide_metal            = nil,
        slide_stone            = nil,
        slide_wood             = nil,
        unlock                 = "doors_door_unlocking",
    },
    gate = {
        close                  = "doors_fencegate_close",
        close_stone            = "mcl_fences_nether_brick_fence_gate_close",
        close_wood             = "doors_fencegate_close",
        locked                 = "doors_door_locked",
        locked_wood            = "doors_door_locked",
        open                   = "doors_fencegate_open",
        open_stone             = "mcl_fences_nether_brick_fence_gate_open",
        open_wood              = "doors_fencegate_open",
    },
    chest = {
        close                  = nil,
        locked                 = "hades_chests_locked",
        open                   = nil,
    },
    lever = {
        up                     = nil,
        down                   = nil,
        fail                   = nil,
    },

    env = {
        bones                  = nil,
        creak                  = nil,
        smoke                  = nil,

        explosive = {
            boom               = "mobs_explode",
            boom_light         = "mobs_fireball",
            boom_heavy         = "mobs_explode",
            ignite_fuse        = nil,
            ignite_powder      = nil,
        },
        fire = {
            burn               = nil,
            burn_light         = nil,
            burn_heavy         = nil,
            combust            = nil,
            extinguish         = "fire_extinguish_flame",
            flame              = "hades_furnaces_burning",
            flame_light        = nil,
            flame_heavy        = nil,
        },
        lava = {
            cool               = "default_cool_lava",
            flow               = nil,
            flow_light         = nil,
            flow_heavy         = nil,
            splash             = nil,
            splash_light       = nil,
            splash_heavy       = nil,
        },
        liquid = {
            bubble             = nil,
            bubble_light       = nil,
            bubble_heavy       = nil,
            drain              = "hades_liquidtanks_take_water",
            drip               = "drippingwater_drip",
            drip_light         = nil,
            drip_heavy         = "drippingwater_drip_on_water",
            fill               = "hades_liquidtanks_fill_water",
            flow               = nil,
            flow_light         = nil,
            flow_heavy         = nil,
            freeze             = nil,
            freeze_light       = nil,
            freeze_heavy       = nil,
            scald              = "drippingwater_drip_on_lava",
            scald_light        = nil,
            scald_heavy        = nil,
            splash             = nil,
            splash_light       = nil,
            splash_heavy       = nil,
            waves              = nil,
            waves_light        = nil,
            waves_heavy        = nil,
        },
        tech = {
            beep               = nil,
            bell               = nil,
            ding               = nil,
            doorbell           = nil,
            hammer             = nil,
        },
        weather = {
            thunder = {
                clap           = nil,
                clap_light     = nil,
                clap_heavy     = nil,
                roll           = nil,
                roll_light     = nil,
                roll_heavy     = nil,
            },
            wind = {
                gust           = nil,
                gust_light     = nil,
                gust_heavy     = nil,
            },
        },
    },

    loop = {
        cook = {
            fry                = nil,
        },
        explosive = {
            burn_fuse          = nil,
            burn_powder        = nil,
        },
        fire = {
            burn               = nil,
            burn_light         = nil,
            burn_heavy         = nil,
            furnace            = "hades_furnaces_burning",
        },
        lava = {
            bubble             = "hades_env_sounds_lava_source",
            bubble_light       = nil,
            bubble_heavy       = nil,
            flow               = "hades_env_sounds_flowing_lava",
            flow_light         = nil,
            flow_heavy         = nil,
        },
        liquid = {
            boil               = nil,
            boil_light         = nil,
            boil_heavy         = nil,
            bubble             = nil,
            bubble_light       = nil,
            bubble_heavy       = nil,
            flow               = "env_sounds_water",
            flow_light         = nil,
            flow_heavy         = nil,
            waves              = nil,
            waves_light        = nil,
            waves_heavy        = nil,
        },
        tech = {
            bell               = nil,
            bells              = nil,
            microwave          = nil,
            oven               = nil,
        },
        weather = {
            rain               = nil,
            rain_light         = nil,
            rain_heavy         = nil,
            snow               = nil,
            snow_light         = nil,
            snow_heavy         = nil,
            wind               = "hades_sounds_atmos_wind",
            wind_light         = nil,
            wind_heavy         = nil,
        },
    },

    notify = {
        default                = "hades_greeting_message",
        achievement            = nil,
        click                  = nil,
        click_alt              = nil,
        ding                   = "hades_beds_set_spawn",
        drink                  = "survival_thirst_drink",
        eat                    = "hbhunger_eat_generic",
        err                    = nil,
        experience             = nil,
        greeting               = "hades_greeting_message",
        level_up               = nil,
        level_down             = nil,
        mode                   = "hades_movement_change_jump_mode",
        ping                   = "hades_greeting_message",
        respawn                = "hades_player_respawn",
        skin                   = nil,
        teleport               = nil,
        toast                  = nil,
        trash                  = "hades_trash_empty",

        gui = {
            button             = "hades_player_gui_button",
            select             = "hades_player_gui_dropdown_select",
            tab                = "hades_player_gui_tab",
        },
    },
}

return sound_api
