local sound_api = {
    node_sound_default         = default.node_sound_defaults,
    node_sound_stone_defaults  = default.node_sound_stone_defaults,
    node_sound_dirt_defaults   = default.node_sound_dirt_defaults,
    node_sound_grass_defaults  = default.node_sound_dirt_defaults,
    node_sound_sand_defaults   = default.node_sound_sand_defaults,
    node_sound_gravel_defaults = default.node_sound_gravel_defaults,
    node_sound_wood_defaults   = default.node_sound_wood_defaults,
    node_sound_leaves_defaults = default.node_sound_leaves_defaults,
    node_sound_glass_defaults  = default.node_sound_glass_defaults,
    node_sound_ice_defaults    = default.node_sound_ice_defaults,
    node_sound_metal_defaults  = default.node_sound_metal_defaults,
    node_sound_water_defaults  = default.node_sound_water_defaults,
    node_sound_lava_defaults   = default.node_sound_water_defaults,
    node_sound_snow_defaults   = default.node_sound_snow_defaults,
    node_sound_wool_defaults   = default.node_sound_defaults,


    node = {
        dig = {
            default            = "default_dig_oddly_breakable_by_hand",
            bushy              = "default_dig_snappy",
            choppy             = "default_dig_choppy",
            clanky             = "default_dig_metal",
            cracky             = "default_ice_dig",
            crumbly            = "default_dig_crumbly",
            earthy             = "default_dig_crumbly",
            fleshy             = nil,
            glassy             = "default_glass_footstep",
            grassy             = "default_dig_crumbly",
            icy                = "default_ice_dig",
            pebbly             = "default_gravel_dig",
            sandy              = "default_dig_crumbly",
            seedy              = nil,
            snappy             = "default_dig_snappy",
            snowy              = "default_dig_crumbly",
            splashy            = nil,
            stony              = "default_dig_choppy",
            wooly              = "default_dig_crumbly",
        },
        dug = {
            default            = "default_dug_node",
            bushy              = nil,
            choppy             = "default_dug_node",
            clanky             = "default_dug_metal",
            cracky             = "default_ice_dug",
            crumbly            = "default_dug_node",
            earthy             = "default_dug_node",
            fleshy             = "default_dug_node",
            glassy             = "default_break_glass",
            grassy             = "default_dug_node",
            icy                = "default_ice_dug",
            pebbly             = "default_gravel_dug",
            sandy              = "default_dug_node",
            seedy              = nil,
            snappy             = "default_dug_node",
            snowy              = "default_dug_node",
            splashy            = nil,
            stony              = "default_dug_node",
            wooly              = "default_dug_node",
        },
        place = {
            default            = "default_place_node",
            bushy              = "default_place_node",
            choppy             = "default_place_node",
            clanky             = "default_place_node_metal",
            cracky             = "default_place_node",
            crumbly            = "default_place_node",
            earthy             = "default_place_node",
            fleshy             = "default_place_node",
            glassy             = "default_glass_footstep",
            grassy             = "default_place_node",
            icy                = "default_place_node",
            pebbly             = "default_place_node",
            sandy              = "default_place_node",
            seedy              = "default_place_node",
            snappy             = "default_place_node",
            snowy              = "default_place_node",
            splashy            = nil,
            stony              = "default_place_node_hard",
            wooly              = "default_place_node",
        },
        step = {
            default            = "default_dirt_footstep",
            bouncy             = nil,
            bushy              = "default_grass_footstep",
            choppy             = "default_wood_footstep",
            clanky             = "default_metal_footstep",
            cracky             = "default_ice_footstep",
            crumbly            = "default_dirt_footstep",
            earthy             = "default_dirt_footstep",
            glassy             = "default_glass_footstep",
            grassy             = "default_grass_footstep",
            icy                = "default_ice_footstep",
            muddy              = nil,
            pebbly             = "default_gravel_footstep",
            sandy              = "default_sand_footstep",
            snappy             = "default_wood_footstep",
            snowy              = "default_snow_footstep",
            splashy            = "default_water_footstep",
            squishy            = nil,
            stony              = "default_hard_footstep",
            wooly              = "default_grass_footstep",

            ladder = {
                default        = nil,
                metal          = nil,
                wood           = nil,
            },
        },
    },

    entity = {
        damage = {
            default            = "player_damage",
            player             = "player_damage",
            player_fall        = "player_damage",
            bony               = "player_damage",
            choppy             = "player_damage",
            clanky             = "player_damage",
            cracky             = "player_damage",
            crumbly            = "player_damage",
            earthy             = "player_damage",
            fleshy             = "player_damage",
            glassy             = "player_damage",
            icy                = "player_damage",
            pebbly             = "player_damage",
            sandy              = "player_damage",
            snappy             = "player_damage",
            snowy              = "player_damage",
            splashy            = "player_damage",
            stony              = "player_damage",
            wooly              = "player_damage",
        },
        die = {
            default            = nil,
            player             = nil,
            bony               = nil,
            choppy             = nil,
            clanky             = nil,
            cracky             = nil,
            crumbly            = nil,
            earthy             = nil,
            fleshy             = nil,
            glassy             = nil,
            icy                = nil,
            pebbly             = nil,
            sandy              = nil,
            snappy             = nil,
            snowy              = nil,
            splashy            = nil,
            stony              = nil,
            wooly              = nil,
        },
    },

    item = {
        drop                   = nil,
        pickup                 = nil,

        tool = {
            broken             = "default_tool_breaks",
            flint              = "fire_flint_and_steel",
            hammer             = nil,
            hit                = nil,
            screwdriver        = nil,
            swing              = nil,
            throw              = nil,
            use                = nil,
        },
    },
    door = {
        close                  = "doors_door_close",
        close_bar              = nil,
        close_glass            = "doors_glass_door_close",
        close_metal            = "doors_steel_door_close",
        close_stone            = nil,
        close_wood             = "doors_door_close",
        lock                   = nil,
        locked                 = nil,
        locked_glass           = nil,
        locked_metal           = nil,
        locked_stone           = nil,
        locked_wood            = nil,
        open                   = "doors_door_open",
        open_bar               = nil,
        open_glass             = "doors_glass_door_open",
        open_metal             = "doors_steel_door_open",
        open_stone             = nil,
        open_wood              = "doors_door_open",
        slam                   = "xpanes_steel_bar_door_close",
        slam_glass             = nil,
        slam_metal             = "xpanes_steel_bar_door_close",
        slam_stone             = nil,
        slam_wood              = nil,
        slide                  = "xpanes_steel_bar_door_open",
        slide_glass            = nil,
        slide_metal            = "xpanes_steel_bar_door_open",
        slide_stone            = nil,
        slide_wood             = nil,
        unlock                 = nil,
    },
    gate = {
        close                  = "doors_fencegate_close",
        close_stone            = nil,
        close_wood             = nil,
        locked                 = nil,
        locked_wood            = nil,
        open                   = "doors_fencegate_open",
        open_stone             = nil,
        open_wood              = nil,
    },
    chest = {
        close                  = "default_chest_close",
        locked                 = nil,
        open                   = "default_chest_open",
    },
    lever = {
        up                     = nil,
        down                   = nil,
        fail                   = nil,
    },

    env = {
        bones                  = nil,
        creak                  = nil,
        smoke                  = "default_item_smoke",

        explosive = {
            boom               = "tnt_explode",
            boom_light         = nil,
            boom_heavy         = "tnt_explode",
            ignite_fuse        = "tnt_ignite",
            ignite_powder      = "tnt_ignite",
        },
        fire = {
            burn               = nil,
            burn_light         = nil,
            burn_heavy         = nil,
            combust            = nil,
            extinguish         = "fire_extinguish_flame",
            flame              = nil,
            flame_light        = nil,
            flame_heavy        = nil,
        },
        lava = {
            cool               = "default_cool_lava",
            flow               = "env_sounds_lava",
            flow_light         = nil,
            flow_heavy         = nil,
            splash             = nil,
            splash_light       = nil,
            splash_heavy       = nil,
        },
        liquid = {
            bubble             = nil,
            bubble_light       = nil,
            bubble_heavy       = nil,
            drain              = nil,
            drip               = nil,
            drip_light         = nil,
            drip_heavy         = nil,
            fill               = nil,
            flow               = "env_sounds_water",
            flow_light         = nil,
            flow_heavy         = nil,
            freeze             = nil,
            freeze_light       = nil,
            freeze_heavy       = nil,
            scald              = nil,
            scald_light        = nil,
            scald_heavy        = nil,
            splash             = nil,
            splash_light       = nil,
            splash_heavy       = nil,
            waves              = nil,
            waves_light        = nil,
            waves_heavy        = nil,
        },
        tech = {
            beep               = nil,
            bell               = nil,
            ding               = nil,
            doorbell           = nil,
            hammer             = nil,
        },
        weather = {
            thunder = {
                clap           = nil,
                clap_light     = nil,
                clap_heavy     = nil,
                roll           = nil,
                roll_light     = nil,
                roll_heavy     = nil,
            },
            wind = {
                gust           = nil,
                gust_light     = nil,
                gust_heavy     = nil,
            },
        },
    },

    loop = {
        cook = {
            fry                = nil,
        },
        explosive = {
            burn_fuse          = "tnt_gunpowder_burning",
            burn_powder        = "tnt_gunpowder_burning",
        },
        fire = {
            burn               = "fire_fire",
            burn_light         = "fire_small",
            burn_heavy         = "fire_large",
            furnace            = "default_furnace_active",
        },
        lava = {
            bubble             = nil,
            bubble_light       = nil,
            bubble_heavy       = nil,
            flow               = nil,
            flow_light         = nil,
            flow_heavy         = nil,
        },
        liquid = {
            boil               = nil,
            boil_light         = nil,
            boil_heavy         = nil,
            bubble             = nil,
            bubble_light       = nil,
            bubble_heavy       = nil,
            flow               = "env_sounds_water",
            flow_light         = nil,
            flow_heavy         = nil,
            waves              = nil,
            waves_light        = nil,
            waves_heavy        = nil,
        },
        tech = {
            bell               = nil,
            bells              = nil,
            microwave          = nil,
            oven               = nil,
        },
        weather = {
            rain               = nil,
            rain_light         = nil,
            rain_heavy         = nil,
            snow               = nil,
            snow_light         = nil,
            snow_heavy         = nil,
            wind               = nil,
            wind_light         = nil,
            wind_heavy         = nil,
        },
    },

    notify = {
        default                = nil,
        achievement            = nil,
        click                  = nil,
        click_alt              = nil,
        ding                   = nil,
        drink                  = nil,
        eat                    = nil,
        err                    = nil,
        experience             = nil,
        greeting               = nil,
        level_up               = nil,
        level_down             = nil,
        mode                   = nil,
        ping                   = nil,
        respawn                = nil,
        skin                   = nil,
        teleport               = nil,
        toast                  = nil,
        trash                  = nil,

        gui = {
            button             = nil,
            select             = nil,
            tab                = nil,
        },
    },
}

return sound_api
