-- note this file handles mineclonia, mineclone2, and its rename voxelibre

local sound_api = {
    node_sound_default         = mcl_sounds.node_sound_defaults,
    node_sound_stone_defaults  = mcl_sounds.node_sound_stone_defaults,
    node_sound_dirt_defaults   = mcl_sounds.node_sound_dirt_defaults,
    node_sound_grass_defaults  = mcl_sounds.node_sound_dirt_defaults,
    node_sound_sand_defaults   = mcl_sounds.node_sound_sand_defaults,
    node_sound_gravel_defaults = mcl_sounds.node_sound_sand_defaults,
    node_sound_wood_defaults   = mcl_sounds.node_sound_wood_defaults,
    node_sound_leaves_defaults = mcl_sounds.node_sound_leaves_defaults,
    node_sound_glass_defaults  = mcl_sounds.node_sound_glass_defaults,
    node_sound_ice_defaults    = mcl_sounds.node_sound_ice_defaults,
    node_sound_metal_defaults  = mcl_sounds.node_sound_metal_defaults,
    node_sound_water_defaults  = mcl_sounds.node_sound_water_defaults,
    node_sound_lava_defaults   = mcl_sounds.node_sound_lava_defaults,
    node_sound_snow_defaults   = mcl_sounds.node_sound_snow_defaults,
    node_sound_wool_defaults   = mcl_sounds.node_sound_wool_defaults,


    node = {
        dig = {
            default            = "default_dig_oddly_breakable_by_hand",
            bushy              = "default_dig_snappy",
            choppy             = "default_dig_choppy",
            clanky             = "default_dig_metal",
            cracky             = "default_dig_cracky",
            crumbly            = "default_dig_crumbly",
            earthy             = "default_dig_crumbly",
            fleshy             = nil,
            glassy             = "default_glass_footstep",
            grassy             = "default_dig_crumbly",
            icy                = "default_ice_dig",
            pebbly             = "default_gravel_dig",
            sandy              = "default_dig_crumbly",
            seedy              = nil,
            snappy             = "default_dig_snappy",
            snowy              = "mobs_mc_snowman_hurt",
            splashy            = nil,
            stony              = "default_dig_choppy",
            wooly              = "mcl_sounds_cloth",
        },
        dug = {
            default            = "default_dug_node",
            bushy              = nil,
            choppy             = "default_dug_node",
            clanky             = "default_dug_metal",
            cracky             = "default_ice_dug",
            crumbly            = "default_dug_node",
            earthy             = "default_dug_node",
            fleshy             = "default_dug_node",
            glassy             = "default_break_glass",
            grassy             = "default_dug_node",
            icy                = "default_ice_dug",
            muddy              = "mud_place_dug",
            pebbly             = "default_gravel_dug",
            sandy              = "default_dug_node",
            seedy              = nil,
            snappy             = "default_dug_node",
            snowy              = "mobs_mc_snowman_death",
            splashy            = "mcl_sounds_dug_water",
            squishy            = "slimenodes_dug",
            stony              = "default_dug_node",
            wooly              = "default_dug_node",
        },
        place = {
            default            = "default_place_node",
            bushy              = "default_place_node",
            choppy             = "default_place_node_hard",
            clanky             = "default_place_node_metal",
            cracky             = "default_place_node",
            crumbly            = "default_place_node",
            earthy             = "default_place_node",
            fleshy             = "default_place_node",
            glassy             = "default_place_node",
            grassy             = "default_place_node",
            icy                = "default_place_node",
            pebbly             = "default_place_node",
            sandy              = "default_place_node",
            seedy              = "default_place_node",
            snappy             = "default_place_node",
            snowy              = "default_place_node",
            splashy            = "mcl_sounds_place_node_water",
            squishy            = "slimenodes_place",
            stony              = "default_place_node_hard",
            wooly              = "default_place_node",
        },
        step = {
            default            = "default_dirt_footstep",
            bouncy             = nil,
            bushy              = "default_grass_footstep",
            choppy             = "default_wood_footstep",
            clanky             = "default_metal_footstep",
            cracky             = "default_ice_footstep",
            crumbly            = "default_sand_footstep",
            earthy             = "default_dirt_footstep",
            glassy             = "default_glass_footstep",
            grassy             = "default_grass_footstep",
            icy                = "default_ice_footstep",
            muddy              = "mud_footsteps",
            pebbly             = "default_gravel_footstep",
            sandy              = "default_sand_footstep",
            snappy             = "default_grass_footstep",
            snowy              = "pedology_snow_soft_footstep",
            splashy            = "default_water_footstep",
            squishy            = "slimenodes_step",
            stony              = "default_hard_footstep",
            wooly              = "default_grass_footstep",

            ladder = {
                default        = nil,
                metal          = nil,
                wood           = nil,
            },
        },
    },

    entity = {
        damage = {
            default            = "default_punch",
            player             = "player_damage",
            player_fall        = "player_falling_damage",
            bony               = "mobs_mc_skeleton_hurt",
            choppy             = "default_punch",
            clanky             = "default_punch",
            cracky             = "default_punch",
            crumbly            = "default_punch",
            earthy             = "default_punch",
            fleshy             = "default_punch",
            glassy             = "default_punch",
            icy                = "default_punch",
            pebbly             = "default_punch",
            sandy              = "default_punch",
            snappy             = "default_punch",
            snowy              = "mobs_mc_snowman_hurt",
            splashy            = "default_punch",
            stony              = "default_punch",
            wooly              = "default_punch",
        },
        die = {
            default            = nil,
            player             = nil,
            bony               = "mobs_mc_skeleton_death",
            choppy             = nil,
            clanky             = nil,
            cracky             = nil,
            crumbly            = nil,
            earthy             = nil,
            fleshy             = nil,
            glassy             = nil,
            icy                = nil,
            pebbly             = nil,
            sandy              = nil,
            snappy             = nil,
            snowy              = "mobs_mc_snowman_death",
            splashy            = nil,
            stony              = nil,
            wooly              = nil,
        },
    },

    item = {
        drop                   = nil,
        pickup                 = "item_drop_pickup",

        tool = {
            broken             = "default_tool_break",
            flint              = "fire_flint_and_steel",
            hammer             = nil,
            hit                = nil,
            screwdriver        = nil,
            swing              = nil,
            throw              = "mcl_throwing_throw",
            use                = nil,
        },
    },
    door = {
        close                  = "doors_door_close",
        close_bar              = nil,
        close_glass            = nil,
        close_metal            = "doors_steel_door_close",
        close_stone            = nil,
        close_wood             = "doors_door_close",
        lock                   = nil,
        locked                 = nil,
        locked_glass           = nil,
        locked_metal           = nil,
        locked_stone           = nil,
        locked_wood            = nil,
        open                   = "doors_door_open",
        open_bar               = nil,
        open_glass             = nil,
        open_metal             = "doors_steel_door_open",
        open_stone             = nil,
        open_wood              = "doors_door_open",
        slam                   = nil,
        slam_glass             = nil,
        slam_metal             = nil,
        slam_stone             = nil,
        slam_wood              = nil,
        slide                  = nil,
        slide_glass            = nil,
        slide_metal            = nil,
        slide_stone            = nil,
        slide_wood             = "mcl_barrels_default_barrel_open",
        unlock                 = nil,
    },
    gate = {
        close                  = "doors_fencegate_close",
        close_stone            = "mcl_fences_nether_brick_fence_gate_close",
        close_wood             = "doors_fencegate_close",
        locked                 = nil,
        locked_wood            = nil,
        open                   = "doors_fencegate_open",
        open_stone             = "mcl_fences_nether_brick_fence_gate_open",
        open_wood              = "doors_fencegate_open",
    },
    chest = {
        close                  = "default_chest_close",
        close_ender            = "mcl_chests_enderchest_close",
        close_stone            = "mcl_chests_shulker_close",
        locked                 = nil,
        open                   = "default_chest_open",
        open_ender             = "mcl_chests_enderchest_open",
        open_stone             = "mcl_chests_shulker_close",
    },
    lever = {
        up                     = nil,
        down                   = nil,
        fail                   = nil,
    },

    env = {
        bones                  = "mobs_mc_skeleton_random",
        creak                  = nil,
        smoke                  = nil,

        explosive = {
            boom               = "mcl_bows_firework",
            boom_light         = "mcl_bows_firework_soft",
            boom_heavy         = "tnt_explode",
            ignite_fuse        = "tnt_ignite",
            ignite_powder      = "tnt_ignite",
        },
        fire = {
            burn               = nil,
            burn_light         = nil,
            burn_heavy         = nil,
            combust            = nil,
            extinguish         = "fire_extinguish_flame",
            flame              = "mobs_fireball",
            flame_light        = nil,
            flame_heavy        = nil,
        },
        lava = {
            cool               = "default_cool_lava",
            flow               = nil,
            flow_light         = nil,
            flow_heavy         = nil,
            splash             = "mcl_sounds_place_node_water",
            splash_light       = nil,
            splash_heavy       = nil,
        },
        liquid = {
            bubble             = "mcl_brewing_complete",
            bubble_light       = nil,
            bubble_heavy       = nil,
            drain              = nil,
            drip               = "drippingwater_drip",
            drip_light         = nil,
            drip_heavy         = "bloop",
            fill               = "mcl_potions_bottle_fill",
            flow               = nil,
            flow_light         = nil,
            flow_heavy         = nil,
            freeze             = nil,
            freeze_light       = nil,
            freeze_heavy       = nil,
            pour               = "mcl_potions_bottle_pour",
            scald              = "drippingwater_lavadrip",
            scald_light        = "builtin_item_lava",
            scald_heavy        = nil,
            splash             = "watersplash",
            splash_light       = nil,
            splash_heavy       = nil,
            waves              = nil,
            waves_light        = nil,
            waves_heavy        = nil,
        },
        tech = {
            beep               = nil,
            bell               = "mcl_bells_bell_stroke",
            ding               = nil,
            doorbell           = nil,
            hammer             = nil,
        },
        weather = {
            thunder = {
                clap           = "lightning_thunder",
                clap_light     = nil,
                clap_heavy     = nil,
                roll           = nil,
                roll_light     = nil,
                roll_heavy     = nil,
            },
            wind = {
                gust           = nil,
                gust_light     = nil,
                gust_heavy     = nil,
            },
        },
    },

    loop = {
        cook = {
            fry                = nil,
        },
        explosive = {
            burn_fuse          = nil,
            burn_powder        = nil,
        },
        fire = {
            burn               = "fire_fire",
            burn_light         = nil,
            burn_heavy         = "fire_fire",
            furnace            = nil,
        },
        lava = {
            bubble             = nil,
            bubble_light       = nil,
            bubble_heavy       = nil,
            flow               = nil,
            flow_light         = nil,
            flow_heavy         = nil,
        },
        liquid = {
            boil               = nil,
            boil_light         = nil,
            boil_heavy         = nil,
            bubble             = nil,
            bubble_light       = nil,
            bubble_heavy       = nil,
            flow               = nil,
            flow_light         = nil,
            flow_heavy         = nil,
            waves              = nil,
            waves_light        = nil,
            waves_heavy        = nil,
        },
        tech = {
            bell               = nil,
            bells              = nil,
            microwave          = nil,
            oven               = nil,
        },
        weather = {
            rain               = "weather_rain",
            rain_light         = nil,
            rain_heavy         = nil,
            snow               = nil,
            snow_light         = nil,
            snow_heavy         = nil,
            wind               = nil,
            wind_light         = nil,
            wind_heavy         = nil,
        },
    },

    notify = {
        default                = "doc_reveal",
        achievement            = "awards_challenge_complete",
        click                  = nil,
        click_alt              = nil,
        ding                   = nil,
        drink                  = "survival_thirst_drink",
        eat                    = "mcl_hunger_eat",
        err                    = nil,
        experience             = "mcl_experience",
        greeting               = nil,
        level_up               = "mcl_experience_level_up",
        level_down             = nil,
        mode                   = nil,
        ping                   = nil,
        respawn                = nil,
        skin                   = nil,
        teleport               = "mcl_portals_teleport",
        toast                  = "awards_ui_toast_in",
        trash                  = nil,

        gui = {
            button             = nil,
            select             = nil,
            tab                = nil,
        },
    },
}

return sound_api
