local pass = function(soundtable)
    return soundtable
end

local sound_api = {
    node_sound_default         = pass,
    node_sound_stone_defaults  = pass,
    node_sound_dirt_defaults   = pass,
    node_sound_grass_defaults  = pass,
    node_sound_sand_defaults   = pass,
    node_sound_gravel_defaults = pass,
    node_sound_wood_defaults   = pass,
    node_sound_leaves_defaults = pass,
    node_sound_glass_defaults  = pass,
    node_sound_ice_defaults    = pass,
    node_sound_metal_defaults  = pass,
    node_sound_water_defaults  = pass,
    node_sound_lava_defaults   = pass,
    node_sound_snow_defaults   = pass,
    node_sound_wool_defaults   = pass,


    node = {
        dig = {
            default            = nil,
            bushy              = nil,
            choppy             = nil,
            clanky             = nil,
            cracky             = nil,
            crumbly            = nil,
            earthy             = nil,
            fleshy             = nil,
            glassy             = nil,
            grassy             = nil,
            icy                = nil,
            pebbly             = nil,
            sandy              = nil,
            seedy              = nil,
            snappy             = nil,
            snowy              = nil,
            splashy            = nil,
            stony              = nil,
            wooly              = nil,
        },
        dug = {
            default            = nil,
            bushy              = nil,
            choppy             = nil,
            clanky             = nil,
            cracky             = nil,
            crumbly            = nil,
            earthy             = nil,
            fleshy             = nil,
            glassy             = nil,
            grassy             = nil,
            icy                = nil,
            pebbly             = nil,
            sandy              = nil,
            seedy              = nil,
            snappy             = nil,
            snowy              = nil,
            splashy            = nil,
            stony              = nil,
            wooly              = nil,
        },
        place = {
            default            = nil,
            bushy              = nil,
            choppy             = nil,
            clanky             = nil,
            cracky             = nil,
            crumbly            = nil,
            earthy             = nil,
            fleshy             = nil,
            glassy             = nil,
            grassy             = nil,
            icy                = nil,
            pebbly             = nil,
            sandy              = nil,
            seedy              = nil,
            snappy             = nil,
            snowy              = nil,
            splashy            = nil,
            stony              = nil,
            wooly              = nil,
        },
        step = {
            default            = nil,
            bouncy             = nil,
            bushy              = nil,
            choppy             = nil,
            clanky             = nil,
            cracky             = nil,
            crumbly            = nil,
            earthy             = nil,
            glassy             = nil,
            grassy             = nil,
            icy                = nil,
            muddy              = nil,
            pebbly             = nil,
            sandy              = nil,
            snappy             = nil,
            snowy              = nil,
            splashy            = nil,
            squishy            = nil,
            stony              = nil,
            wooly              = nil,

            ladder = {
                default        = nil,
                metal          = nil,
                wood           = nil,
            },
        },
    },

    entity = {
        damage = {
            default            = nil,
            player             = nil,
            player_fall        = nil,
            bony               = nil,
            choppy             = nil,
            clanky             = nil,
            cracky             = nil,
            crumbly            = nil,
            earthy             = nil,
            fleshy             = nil,
            glassy             = nil,
            icy                = nil,
            pebbly             = nil,
            sandy              = nil,
            snappy             = nil,
            snowy              = nil,
            splashy            = nil,
            stony              = nil,
            wooly              = nil,
        },
        die = {
            default            = nil,
            player             = nil,
            bony               = nil,
            choppy             = nil,
            clanky             = nil,
            cracky             = nil,
            crumbly            = nil,
            earthy             = nil,
            fleshy             = nil,
            glassy             = nil,
            icy                = nil,
            pebbly             = nil,
            sandy              = nil,
            snappy             = nil,
            snowy              = nil,
            splashy            = nil,
            stony              = nil,
            wooly              = nil,
        },
    },

    item = {
        drop                   = nil,
        pickup                 = nil,

        tool = {
            broken             = nil,
            flint              = nil,
            hammer             = nil,
            hit                = nil,
            screwdriver        = nil,
            swing              = nil,
            throw              = nil,
            use                = nil,
        },
    },
    door = {
        close                  = nil,
        close_bar              = nil,
        close_stone            = nil,
        close_glass            = nil,
        close_metal            = nil,
        close_wood             = nil,
        lock                   = nil,
        locked                 = nil,
        locked_glass           = nil,
        locked_metal           = nil,
        locked_stone           = nil,
        locked_wood            = nil,
        open                   = nil,
        open_bar               = nil,
        open_glass             = nil,
        open_metal             = nil,
        open_stone             = nil,
        open_wood              = nil,
        slam                   = nil,
        slam_glass             = nil,
        slam_metal             = nil,
        slam_stone             = nil,
        slam_wood              = nil,
        slide                  = nil,
        slide_glass            = nil,
        slide_metal            = nil,
        slide_stone            = nil,
        slide_wood             = nil,
        unlock                 = nil,
    },
    gate = {
        close                  = nil,
        close_stone            = nil,
        close_wood             = nil,
        locked                 = nil,
        locked_wood            = nil,
        open                   = nil,
        open_stone             = nil,
        open_wood              = nil,
    },
    chest = {
        close                  = nil,
        locked                 = nil,
        open                   = nil,
    },
    lever = {
        up                     = nil,
        down                   = nil,
        fail                   = nil,
    },

    env = {
        bones                  = nil,
        creak                  = nil,
        smoke                  = nil,

        explosive = {
            boom               = nil,
            boom_light         = nil,
            boom_heavy         = nil,
            ignite_fuse        = nil,
            ignite_powder      = nil,
        },
        fire = {
            burn               = nil,
            burn_light         = nil,
            burn_heavy         = nil,
            combust            = nil,
            extinguish         = nil,
            flame              = nil,
            flame_light        = nil,
            flame_heavy        = nil,
        },
        lava = {
            cool               = nil,
            flow               = nil,
            flow_light         = nil,
            flow_heavy         = nil,
            splash             = nil,
            splash_light       = nil,
            splash_heavy       = nil,
        },
        liquid = {
            bubble             = nil,
            bubble_light       = nil,
            bubble_heavy       = nil,
            drain              = nil,
            drip               = nil,
            drip_light         = nil,
            drip_heavy         = nil,
            fill               = nil,
            flow               = nil,
            flow_light         = nil,
            flow_heavy         = nil,
            freeze             = nil,
            freeze_light       = nil,
            freeze_heavy       = nil,
            scald              = nil,
            scald_light        = nil,
            scald_heavy        = nil,
            splash             = nil,
            splash_light       = nil,
            splash_heavy       = nil,
            waves              = nil,
            waves_light        = nil,
            waves_heavy        = nil,
        },
        tech = {
            beep               = nil,
            bell               = nil,
            ding               = nil,
            doorbell           = nil,
            hammer             = nil,
        },
        weather = {
            thunder = {
                clap           = nil,
                clap_light     = nil,
                clap_heavy     = nil,
                roll           = nil,
                roll_light     = nil,
                roll_heavy     = nil,
            },
            wind = {
                gust           = nil,
                gust_light     = nil,
                gust_heavy     = nil,
            },
        },
    },

    loop = {
        cook = {
            fry                = nil,
        },
        explosive = {
            burn_fuse          = nil,
            burn_powder        = nil,
        },
        fire = {
            burn               = nil,
            burn_light         = nil,
            burn_heavy         = nil,
            furnace            = nil,
        },
        lava = {
            bubble             = nil,
            bubble_light       = nil,
            bubble_heavy       = nil,
            flow               = nil,
            flow_light         = nil,
            flow_heavy         = nil,
        },
        liquid = {
            boil               = nil,
            boil_light         = nil,
            boil_heavy         = nil,
            bubble             = nil,
            bubble_light       = nil,
            bubble_heavy       = nil,
            flow               = nil,
            flow_light         = nil,
            flow_heavy         = nil,
            waves              = nil,
            waves_light        = nil,
            waves_heavy        = nil,
        },
        tech = {
            bell               = nil,
            bells              = nil,
            microwave          = nil,
            oven               = nil,
        },
        weather = {
            rain               = nil,
            rain_light         = nil,
            rain_heavy         = nil,
            snow               = nil,
            snow_light         = nil,
            snow_heavy         = nil,
            wind               = nil,
            wind_light         = nil,
            wind_heavy         = nil,
        },
    },

    notify = {
        default                = nil,
        achievement            = nil,
        click                  = nil,
        click_alt              = nil,
        ding                   = nil,
        drink                  = nil,
        eat                    = nil,
        err                    = nil,
        experience             = nil,
        greeting               = nil,
        level_up               = nil,
        level_down             = nil,
        mode                   = nil,
        ping                   = nil,
        respawn                = nil,
        skin                   = nil,
        teleport               = nil,
        toast                  = nil,
        trash                  = nil,

        gui = {
            button             = nil,
            select             = nil,
            tab                = nil,
        },
    },
}

return sound_api
