version: "3.6"

x-servicetemplate: &servicetemplate
  build: test
  volumes:
    - "./:/root/.minetest/worlds/world/worldmods/xcompat/"
    - "./test/nodelist:/root/.minetest/worlds/world/nodelist/"
    - "./test/minetest.conf:/minetest.conf"

services:
 minetest_game:
  <<: *servicetemplate
  entrypoint: "minetestserver --config /minetest.conf --world /root/.minetest/worlds/world/ --gameid minetest"

 farlands_reloaded:
  <<: *servicetemplate
  entrypoint: "minetestserver --config /minetest.conf --world /root/.minetest/worlds/world/ --gameid farlands_reloaded"

 mineclonia:
  <<: *servicetemplate
  entrypoint: "minetestserver --config /minetest.conf --world /root/.minetest/worlds/world/ --gameid mineclonia"

 mineclone2:
  <<: *servicetemplate
  entrypoint: "minetestserver --config /minetest.conf --world /root/.minetest/worlds/world/ --gameid mineclone2"

 hades_revisited:
  <<: *servicetemplate
  entrypoint: "minetestserver --config /minetest.conf --world /root/.minetest/worlds/world/ --gameid hades_revisited"
