name: test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
        uses: actions/checkout@main
      - name: test
        run: docker-compose up --exit-code-from default
