name: hades_revisited
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - uses: buckaroobanzay/mtt@main
        with:
          modname: xcompat
          git_game_repo: https://codeberg.org/Wuzzy/Hades_Revisited
          git_dependencies: |
            https://github.com/mt-mods/unifieddyes
            https://github.com/mt-mods/basic_materials
            https://github.com/OgelGames/fakelib
            https://github.com/mt-mods/pipeworks
            https://github.com/mt-mods/steel
            https://github.com/mt-mods/display_modpack
            https://github.com/mt-mods/homedecor_modpack
          additional_config: |
            mtt_nodelist = hades_revisited.txt